import { PDFTool } from './types';

export const TOOLS: PDFTool[] = [
  // AI TOOLS
  {
    id: 'ai-summarizer',
    name: 'AI Summarizer',
    shortDescription: 'Summarize articles, essays, and reports in seconds.',
    description: 'Quickly generate concise summaries from articles, paragraphs, and essays, providing clear and precise key points using Gemini AI.',
    category: 'ai',
    iconName: 'Sparkles',
    isNew: true,
    requiresPro: true,
  },
  {
    id: 'ai-translate',
    name: 'Translate PDF',
    shortDescription: 'Translate your PDF documents powered by Gemini AI.',
    description: 'Easily translate PDF files while keeping fonts, layout, and formatting perfectly intact using advanced Gemini translation models.',
    category: 'ai',
    iconName: 'Languages',
    isNew: true,
    requiresPro: true,
  },
  {
    id: 'ocr',
    name: 'OCR PDF',
    shortDescription: 'Convert scanned PDFs into selectable searchable documents.',
    description: 'Apply Optical Character Recognition (OCR) to scanned PDFs, allowing you to easily copy text and make files searchable.',
    category: 'ai',
    iconName: 'Eye',
    requiresPro: true,
  },

  // ORGANIZE TOOLS
  {
    id: 'merge',
    name: 'Merge PDF',
    shortDescription: 'Combine multiple PDF files into one in any order.',
    description: 'Combine multiple PDFs in the exact order you want with our incredibly easy and fast PDF merge tool.',
    category: 'organize',
    iconName: 'FileStack',
  },
  {
    id: 'split',
    name: 'Split PDF',
    shortDescription: 'Extract specific pages or save each page as a separate PDF.',
    description: 'Separate a single page, a custom range, or every page of your document into individual, independent PDF files.',
    category: 'organize',
    iconName: 'Scissors',
  },
  {
    id: 'organize',
    name: 'Organize PDF',
    shortDescription: 'Reorder, delete, or insert pages into your document.',
    description: 'Sort pages of your PDF file however you like. Delete unwanted PDF pages or inject brand-new pages into your document at your convenience.',
    category: 'organize',
    iconName: 'FolderTree',
  },
  {
    id: 'crop',
    name: 'Crop PDF',
    shortDescription: 'Crop margins of your PDF or select specific sections.',
    description: 'Crop visual margins of PDF documents or crop to specific rectangular regions, then apply globally or to select pages.',
    category: 'organize',
    iconName: 'Crop',
  },

  // CONVERT FROM PDF
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    shortDescription: 'Convert PDF files into editable DOCX files.',
    description: 'Easily convert your PDF files into easy-to-edit DOCX documents with high layout accuracy.',
    category: 'convert',
    iconName: 'FileWord',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    shortDescription: 'Convert PDF files into customizable PPTX slides.',
    description: 'Turn your PDF files into fully editable PowerPoint PPTX slideshows for seamless presentations.',
    category: 'convert',
    iconName: 'FileSliders',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    shortDescription: 'Extract table structures straight to spreadsheets.',
    description: 'Pull data and spreadsheet tables straight from PDFs into fully structured XLS or XLSX spreadsheets in a few seconds.',
    category: 'convert',
    iconName: 'FileSpreadsheet',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    shortDescription: 'Convert each PDF page into a high-quality image.',
    description: 'Convert every individual PDF page into a JPG image, or extract embedded image assets residing in the document.',
    category: 'convert',
    iconName: 'Image',
  },

  // CONVERT TO PDF
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    shortDescription: 'Convert Word DOC/DOCX files directly into PDF.',
    description: 'Make DOC and DOCX files easy to share and read by converting them to pristine PDF files instantly.',
    category: 'convert',
    iconName: 'FileCheck',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    shortDescription: 'Convert PowerPoint files directly into PDF.',
    description: 'Convert PPT and PPTX presentations into highly-compatible PDFs that look perfect on any device.',
    category: 'convert',
    iconName: 'FileCode',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    shortDescription: 'Convert Excel spreadsheets directly into PDF.',
    description: 'Turn spreadsheet tables and data charts from XLSX/XLS files into perfectly paginated and clean PDFs.',
    category: 'convert',
    iconName: 'Table',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    shortDescription: 'Convert JPG, PNG, or GIF images into PDF in seconds.',
    description: 'Convert JPG and standard image formats into PDFs in seconds. Adjust orientation, page sizing, and margins easily.',
    category: 'convert',
    iconName: 'FileImage',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    shortDescription: 'Convert active web links or pages into PDFs.',
    description: 'Convert standard web pages into PDFs. Copy and paste the target web URL and convert it into a download with a single click.',
    category: 'convert',
    iconName: 'Globe',
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    shortDescription: 'Scan printed papers using your webcam or scanner.',
    description: 'Capture document scans using your system camera or local scanner and compile them instantly into a clean PDF.',
    category: 'convert',
    iconName: 'Camera',
  },

  // OPTIMIZE & EDIT
  {
    id: 'compress',
    name: 'Compress PDF',
    shortDescription: 'Reduce file size while preserving maximal resolution.',
    description: 'Optimize your PDF sizes while maintaining clean vector typography and image resolutions.',
    category: 'edit',
    iconName: 'FileArchive',
  },
  {
    id: 'edit',
    name: 'Edit PDF',
    shortDescription: 'Add rich text, shapes, or freehand drawings directly.',
    description: 'Add text annotations, images, vector shapes, or freehand canvas drawings directly on your PDF pages.',
    category: 'edit',
    iconName: 'Edit3',
  },
  {
    id: 'watermark',
    name: 'Watermark PDF',
    shortDescription: 'Stamp customized overlay text or image over pages.',
    description: 'Stamp a custom text line or image over your PDF. Configure transparency, sizing, fonts, and grid placements.',
    category: 'edit',
    iconName: 'ShieldAlert',
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    shortDescription: 'Rotate individual pages or entire documents.',
    description: 'Rotate your PDF pages 90, 180, or 270 degrees. Support batch page rotations on multiple documents simultaneously.',
    category: 'edit',
    iconName: 'RotateCw',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    shortDescription: 'Add page numbers with custom layout alignments.',
    description: 'Add sequentially generated page numbers into your PDF with customized fonts, positioning, offsets, and dimensions.',
    category: 'edit',
    iconName: 'Hash',
  },

  // SECURITY & RELIABILITY
  {
    id: 'sign',
    name: 'Sign PDF',
    shortDescription: 'Sign yourself or request verified digital signatures.',
    description: 'Add your own electronic signatures (handdrawn or typed), stamp initials, or create verified fillable signature requests.',
    category: 'security',
    iconName: 'PenTool',
  },
  {
    id: 'protect',
    name: 'Protect PDF',
    shortDescription: 'Encrypt your document with a secure user password.',
    description: 'Add high-grade password encryption to your PDF document to protect sensitive info from unauthorized viewers.',
    category: 'security',
    iconName: 'Lock',
  },
  {
    id: 'unlock',
    name: 'Unlock PDF',
    shortDescription: 'Decrypt and remove password locks from files.',
    description: 'Remove password protection, letting you view and print files with standard accessibility.',
    category: 'security',
    iconName: 'Unlock',
  },
  {
    id: 'repair',
    name: 'Repair PDF',
    shortDescription: 'Recover text content and fix corrupted PDF tables.',
    description: 'Analyze and reconstruct damaged, corrupted, or unreadable PDF page formats and recover maximum data.',
    category: 'security',
    iconName: 'Activity',
  },
  {
    id: 'compare',
    name: 'Compare PDF',
    shortDescription: 'Spot side-by-side differences between file versions.',
    description: 'Compare two PDFs in an elegant side-by-side view with visual heatmaps indicating added or removed content.',
    category: 'security',
    iconName: 'Columns',
  },
  {
    id: 'redact',
    name: 'Redact PDF',
    shortDescription: 'Black-out or wipe sensitive visual records.',
    description: 'Permanently redact private texts, graphics, or names from your document, keeping them completely safe.',
    category: 'security',
    iconName: 'EyeOff',
  },
  {
    id: 'forms',
    name: 'PDF Forms',
    shortDescription: 'Create interactive fillable fields, checkboxes, or fill surveys.',
    description: 'Create interactive text fields, drop-downs, multiple choices, and checkboxes. Fill out existing fields or compile blank forms.',
    category: 'security',
    iconName: 'CheckSquare',
    isNew: true,
  },
  {
    id: 'pdf-to-pdfa',
    name: 'PDF to PDF/A',
    shortDescription: 'Transform standard document structures to long-term PDF/A.',
    description: 'Transform standard PDFs into the ISO-compliant PDF/A archive format, ensuring future readability.',
    category: 'security',
    iconName: 'Archive',
  },
];
